[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  included_files = ["*.csv", "*.json"]

[dev]
  command = "npm run dev:vite"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
