[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  included_files = ["functions/_data/*", "functions/_shared/*.cjs"]

[dev]
  command = "npm run dev:vite"
  port = 3000
  targetPort = 5173
